### ISSUE TITLE
edit page's updating database doesn't work

### ISSUE THREAD

**Issue by selfdeception** [selfdeception/read_it#2]
the model: 110-137

1. console log's from the update controller (prior to promise returned from model)
2. console log's from update model prior to the DB query
3. database remains unchanged after an update when checked with SQL

No error messages.

**Comment by irwintsay** [comment]
How far is your update data reaching in the edit page form -> model -> database chain?

**Comment by selfdeception** [comment]
THE ERROR OCCURS HERE
model-->database

**Comment by irwintsay** [comment]
So your able to console.log the data before you sent it along your pg-promise query?

**Comment by selfdeception** [comment]
yes... also I am uploading migrations here now.

**Comment by irwintsay** [comment]
If this issue is resolved then I'll go ahead and close it
